project_id = "mlyostzsjvqlcczdunet"

[functions.reserve]
verify_jwt = false

[functions.webhook-mercadopago]
verify_jwt = false

[functions.expire-reservations]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false
